I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 269, in script
    pause
  File "renpy/common/000statements.rpy", line 462, in execute_pause
    renpy.pause()
  File "game/frame.rpy", line 294, in execute
    screen think(position,emotion,atl=None):
  File "game/frame.rpy", line 294, in execute
    screen think(position,emotion,atl=None):
  File "game/frame.rpy", line 296, in execute
    frame at atl:
  File "game/frame.rpy", line 304, in execute
    if random_num == 1:
  File "game/frame.rpy", line 304, in <module>
    if random_num == 1:
NameError: name 'random_num' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 269, in script
    pause
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1974, in execute
    self.call("execute")
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 462, in execute_pause
    renpy.pause()
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\exports\statementexports.py", line 194, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/frame.rpy", line 294, in execute
    screen think(position,emotion,atl=None):
  File "game/frame.rpy", line 294, in execute
    screen think(position,emotion,atl=None):
  File "game/frame.rpy", line 296, in execute
    frame at atl:
  File "game/frame.rpy", line 304, in execute
    if random_num == 1:
  File "game/frame.rpy", line 304, in <module>
    if random_num == 1:
NameError: name 'random_num' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Ushio_Noa 0.1.0_beta
Sat Nov  2 16:14:25 2024
